### ISSUE TITLE
Problems with the Finnish translation

### ISSUE THREAD

**Issue by jkinnunen** [javidominguez/screenshots#17]
There is something wrong with the Finnish translation. The problematic strings are:

Viiteobjekti kattaa {ratio} % suorakulmiosta (Poedit displays the following translation warning: format specifications in 'msgid' and 'msgstr' for argument 1 are not the same)
Suorakulmio kattaa {percentage} % näytöstä (Poedit displays the following translation warning: 'msgstr' is not a valid Python format string, unlike 'msgid'. Reason: In the directive number 1, the character 'n' is not a valid conversion specifier.)

I have checked the strings, but didn't find any errors.

**Comment by javidominguez** [comment]
These messages contain the % (percent) sign that is used as a formatting marker but here it functions as a percent symbol next to a number that expresses a proportion x/100. Some languages put the sign before the number and others after it. Poedit does not interpret it correctly so it warns (maybe I should have escaped it with \%) but it is not an error.

See a discussion of this topic in #9.

**Comment by jkinnunen** [comment]
Ok, thanks for the explanation. So there's nothing wrong in those translated strings, then.
